# Generated by Django 5.2 on 2025-09-06 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('grupo_muscular', models.CharField(blank=True, max_length=60)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('objetivo', models.CharField(blank=True, max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_creadas', to='socios.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='RutinaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField()),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='rutina.rutina')),
            ],
            options={
                'verbose_name': 'Día de rutina',
                'verbose_name_plural': 'Días de rutina',
                'unique_together': {('rutina', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='RutinaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('series', models.PositiveIntegerField(blank=True, null=True)),
                ('repeticiones', models.PositiveIntegerField(blank=True, null=True)),
                ('tiempo_seg', models.PositiveIntegerField(blank=True, null=True)),
                ('descanso_seg', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_rutinas', to='rutina.ejercicio')),
                ('rutina_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rutina.rutinadia')),
            ],
            options={
                'verbose_name': 'Detalle de rutina',
                'verbose_name_plural': 'Detalles de rutina',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RutinaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Vigente', 'Vigente'), ('Finalizada', 'Finalizada'), ('Pausada', 'Pausada')], default='Vigente', max_length=20)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='rutina.rutina')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Asignación de rutina',
                'verbose_name_plural': 'Asignaciones de rutina',
                'indexes': [models.Index(fields=['socio', 'fecha_inicio', 'fecha_fin'], name='rutina_ruti_socio_i_5134e3_idx')],
            },
        ),
    ]
