# Generated by Django 5.2 on 2025-09-06 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Debito', 'Débito'), ('Credito', 'Crédito'), ('Transferencia', 'Transferencia'), ('MP', 'Mercado Pago')], max_length=30)),
                ('comprobante', models.CharField(blank=True, max_length=60, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='socios.suscripcion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
