# Generated by Django 5.2 on 2025-09-13 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socio',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='socio',
            name='socios_soci_sucursa_b1ea7b_idx',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='telefono',
        ),
        migrations.AddField(
            model_name='socio',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='socio',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='socio',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='socio',
            name='sucursal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='socio',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_socio', to=settings.AUTH_USER_MODEL),
        ),
    ]
