# Generated by Django 5.2 on 2025-09-15 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_alter_socio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='sucursal',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='socios.sucursal'),
        ),
    ]
