# Generated by Django 5.2 on 2025-10-12 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_alter_socio_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='dni',
            field=models.CharField(help_text='Este será tu usuario para iniciar sesión.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,10}$', message='El DNI debe contener solo números (7 a 10 dígitos).')]),
        ),
    ]
