# Generated by Django 5.2 on 2025-10-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_alter_socio_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de pago'), ('Vigente', 'Vigente'), ('Vencida', 'Vencida'), ('Pausada', 'Pausada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
