# Generated by Django 5.2.7 on 2025-11-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_alter_suscripcion_estado_alter_suscripcion_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
