# Generated by Django 5.2 on 2025-09-06 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10)),
                ('origen', models.CharField(choices=[('Molturno', 'Molturno'), ('Recepcion', 'Recepción'), ('Manual', 'Manual')], default='Recepcion', max_length=20)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='socios.socio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='socios.sucursal')),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['sucursal', 'fecha_hora'], name='ocupacion_a_sucursa_e3d0a7_idx'), models.Index(fields=['socio', 'fecha_hora'], name='ocupacion_a_socio_i_724134_idx')],
            },
        ),
    ]
