# Generated by Django 5.2 on 2025-09-16 02:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocupacion', '0001_initial'),
        ('socios', '0003_alter_socio_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('device_id', models.CharField(blank=True, max_length=64, null=True)),
                ('raw_uid', models.CharField(blank=True, max_length=128, null=True)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socios.socio')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_at', models.DateTimeField()),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='socios.socio')),
            ],
        ),
        migrations.DeleteModel(
            name='Acceso',
        ),
    ]
