# Generated by Django 5.2 on 2025-09-16 03:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocupacion', '0002_accessevent_activesession_delete_acceso'),
        ('socios', '0003_alter_socio_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socios.socio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socios.sucursal')),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
            },
        ),
        migrations.DeleteModel(
            name='AccessEvent',
        ),
        migrations.AddIndex(
            model_name='acceso',
            index=models.Index(fields=['socio', 'sucursal', 'fecha_hora'], name='ocupacion_a_socio_i_c0ca4a_idx'),
        ),
    ]
